import Carousel from '@/components/Carousel'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import Link from 'next/link'


export const getStaticProps = async()=>{
  const res = await fetch('https://jsonplaceholder.typicode.com/posts')
  const data = await res.json()

  return {
    props:{
      data,
    }
  }
}

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>My Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Carousel />
      {data.slice(0,7).map((curEle)=>{
        return (
          <div key={curEle.id}>
            <Link href={`/demo/${curEle.id}`}><div>{curEle.title}</div></Link>
          </div>
        )
      })}
    </>
  )
}
